services:
  - type: web
    name: hattrick-flask-api
    runtime: python
    rootDir: flask_api
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
